on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1
          elixir-version: 1.9.4
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-deps-
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-mix-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-mix-build-
      - run: mix deps.get
      - run: make check
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - run: make docker
      - run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && \
          docker push docker.pkg.github.com/zhulik/elixir_syncthing_bot/elixir_syncthing_bot:latest
